### User API
get https://ngo-event-hub-hksp.vercel.app/user-api/users


###
get https://ngo-event-hub-hksp.vercel.app/user-api/users/org


###
post https://ngo-event-hub-hksp.vercel.app/user-api/register
Content-Type: application/json

{
    "username": "nikitha_1710",
    "password": "nikitha1710", 
    "type": "personal",
    "details": {
    "name": "Potluri Nikitha",
    "mobileNumber": "9123456789",
    "email": "nikitha@gmail.com"
    }
}


###
post https://ngo-event-hub-hksp.vercel.app/user-api/login
Content-Type: application/json

{
    
    "username":"org1",
    "password":"1234567890"
   
}


###
put https://ngo-event-hub-hksp.vercel.app/user-api/update
Content-Type: application/json

{
    "username": "org",
    "password": "1234567890", 
    "type": "organization",
    "details": {
    "name": "Orga NGO",
    "mobileNumber": "9123456789",
    "email": "org@gmail.com"
    },
    "organizationDetails": {
      "place": "New Delhi",
      "description": "This is a good organization." 
    }
}

###
get https://ngo-event-hub-hksp.vercel.app/user-api/user-counts



### Events API
get https://ngo-event-hub-hksp.vercel.app/event-api/events


###
get https://ngo-event-hub-hksp.vercel.app/event-api/events/organization/org


###
post https://ngo-event-hub-hksp.vercel.app/event-api/create
Content-Type: application/json

{
  "username": {
    //userdetails
  },
  "name": "Charity 2025",
  "description": "Join us for a charity run to support underprivileged children.",
  "location": "Central Park, CityName 1",
  "date": "1th January 2025",
  "timings": "10:00 AM - 1:00 PM",
  "registerLink": "http://charityrun20251.com/register",
  "paymentLink": "123-456-7890"
}


###
delete https://ngo-event-hub-hksp.vercel.app/event-api/delete/67812dd0ad93e4ed818aba3d